
player_defaults = dict(id = 0
                       , second_name = "N/A", first_name = "N/A"
                       , chance_of_playing_next_round = 0
                       , chance_of_playing_this_round = 0
                       , code = 0
                       , cost_change_event = 0
                       , cost_change_event_fall = 0
                       , cost_change_start = 0
                       , cost_change_start_fall = 0
                       , dreamteam_count = 0
                       , element_type = 0
                       , ep_next = "N/A"
                       , ep_this = "N/A"
                       , event_points = 0
                       , form = "N/A"
                       , in_dreamteam = False
                       , news = "N/A"
                       , news_added = "N/A"
                       , now_cost = 0
                       , photo = "N/A"
                       , points_per_game = "N/A"
                       , selected_by_percent = "N/A"
                       , special = False
                       , squad_number = 0
                       , status = "N/A"
                       , team = 0
                       , team_code = 0
                       , total_points = 0
                       , transfers_in = 0
                       , transfers_in_event = 0
                       , transfers_out = 0
                       , transfers_out_event = 0
                       , value_form = "N/A"
                       , value_season = "N/A"
                       , web_name = "N/A"
                       , minutes = 0
                       , goals_scored = 0
                       , assists = 0
                       , clean_sheets = 0
                       , goals_conceded = 0
                       , own_goals = 0
                       , penalties_saved = 0
                       , penalties_missed = 0
                       , yellow_cards = 0
                       , red_cards = 0
                       , saves = 0
                       , bonus = 0
                       , bps = 0
                       , influence = "N/A"
                       , creativity = "N/A"
                       , threat = "N/A"
                       , ict_index = "N/A"
                       , influence_rank = 0
                       , influence_rank_type = 0
                       , creativity_rank = 0
                       , creativity_rank_type = 0
                       , threat_rank = 0
                       , threat_rank_type = 0
                       , ict_index_rank = 0
                       , ict_index_rank_type = 0
                       , corners_and_indirect_freekicks_order = 0
                       , corners_and_indirect_freekicks_text = "N/A"
                       , direct_freekicks_order = 0
                       , direct_freekicks_text = "N/A"
                       , penalties_order = 0
                       , penalties_text = "N/A"
                       )
player_history_defaults = dict(player = 0
                            ,season_name = "N/A"
                            ,element_code = 0
                            ,start_cost = 0
                            ,end_cost = 0
                            ,total_points = 0
                            ,minutes = 0
                            ,goals_scored = 0
                            ,assists = 0
                            ,clean_sheets = 0
                            ,goals_conceded = 0
                            ,own_goals = 0
                            ,penalties_saved = 0
                            ,penalties_missed = 0
                            ,yellow_cards = 0
                            ,red_cards = 0
                            ,saves = 0
                            ,bonus = 0
                            ,bps = 0
                            ,influence = "N/A"
                            ,creativity = "N/A"
                            ,threat = "N/A"
                            ,ict_index = "N/A")
