# Generated by Django 3.2.6 on 2021-09-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions_squads_players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ManyToManyField(related_name='squads', to='competitions_squads_players.Player')),
            ],
        ),
    ]
