# Generated by Django 3.2.6 on 2021-09-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenizeduser',
            name='fav_colour',
        ),
        migrations.AlterField(
            model_name='tokenizeduser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='tokenizeduser',
            name='username',
            field=models.CharField(db_index=True, max_length=40, unique=True),
        ),
    ]
